services:
  wordpress:
    environment:
      # NGINX proxy + SSL
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80
    networks:
      - corevega-net

  db:
    networks:
      - corevega-net

networks:
  corevega-net:
    external: true
