services:
  wordpress:
    ports:
      - "9020:80"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: solreason-phpmyadmin
    restart: unless-stopped
    ports:
      - "9021:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
